
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_ERROR = "SET_USER_ERROR";

export const GET_SINGLE_USER_REQUEST = "GET_SINGLE_USER_REQUEST";
export const SET_SINGLE_USER_DATA = "SET_SINGLE_USER";
export const SET_SINGLE_USER_ERROR = "SET_SINGLE_USER_ERROR";

export const CHANGE_PAGE = "CHANGE_PAGE";